CREATE OR REPLACE PROCEDURE transform.sp_postgres_delta()
returns variant 
language javascript 
EXECUTE AS CALLER 
    as 
    $$
        var results = [];
        
        // set enviornment 
        var db_set_env = snowflake.createStatement({sqlText : "use db_postgres_share"});
        db_set_env.execute();
    
        
        // defining truncate statements 
        var truncate_table = snowflake.createStatement({sqlText : "truncate table db_postgres_share.raw.first_leads_delta"});
        truncate_table.execute();
        
        var copy_into = snowflake.createStatement({sqlText: "copy into raw.first_leads_delta from @transform.stg_postgres/postgres-delta ON_ERROR = 'CONTINUE'"});
        copy_into.execute();
    
        var merge_statement = `MERGE INTO raw.first_leads as a USING raw.first_leads_delta as b ON a.id = b.id
                               WHEN MATCHED THEN 
                               UPDATE SET 
                                a.dateACC = b.dateAcc, 
                                a.TimeACC = b.TimeAcc, 
                                a.VanillaSoft_ID = b.VanillaSoft_ID, 
                                a.VanillaSoft_Date = b.VanillaSoft_Date, 
	                              a.VanillaSoft_Time = b.VanillaSoft_Time, 
                                a.VanisllaSoft_Results = b.VanisllaSoft_Results, 
                                a.EverFlow_Trans_Id = b.EverFlow_Trans_Id, 
                                a.Offer_ID = b.Offer_ID , 
                                a.Category= b.Category , 
	                              a.Channel = b.Channel, 
                                a.ad_Network= b.ad_Network, 
                                a.Aff_id= b.Aff_id,
                                a.Aff_Source = b.Aff_Source,
                                a.Sub_1 = b.Sub_1,
                                a.Sub_2 = b.Sub_2,
                                a.Sub_3 = b.Sub_3,
                                a.Sub_4 = b.Sub_4,
	                              a.Sub_5 = b.Sub_5,
                                a.ip_address = b.ip_address,
                                a.First_Name = b.First_Name,
                                a.Last_Name  = b.Last_Name,
                                a.Email = b.Email, 
                                a.Phone = b.Phone,
                                a.State = b.State,
                                a.Zip = b.Zip,
	                              a.Klaviyo_ID = b.Klaviyo_ID,
                                a.Debt_Amount = b.Debt_Amount,
                                a.gclid = b.gclid,
                                a.msclkid = b.msclkid,
                                a.Missed_Apts = b.Missed_Apts,
                                a.chat_start = b.chat_start,
	                              a.Quoted_date = b.Quoted_date,
                                a.Quoted_Time = b.Quoted_Time,
                                a.bad_info = b.bad_info,
                                a.dnq = b.dnq,
                                a.dnc = b.dnc,
                                a.sold= b.sold,
                                a.posted_to  = b.posted_to,
	                              a.pushed_to = b.pushed_to,
                                a.push_time = b.push_time,
                                a.push_date= b.push_date,
                                a.tcpa_date = b.tcpa_date,
                                a.tcpa_screenshot = b.tcpa_screenshot,
	                              a.duplicate = b.duplicate,
                                a.payout = b.payout,
                                a.activecampaign_id= b.activecampaign_id,
                                a.ls_tracking= b.ls_tracking,
                                a.vs_lead_status = b.vs_lead_status,
                                a.tcpa_time = b.tcpa_time,
                                a.posted_to2  = b.posted_to2,
                                a.website = b.website,
                                a.op = b.op,
                                a.result_code  = b.result_code,
                                a.token = b.token,
                                a.date_reactivated = b.date_reactivated, 
                                a.chat_notes= b.chat_notes, 
                                a.original_lead_source= b.original_lead_source, 
                                a.callback_notes = b.callback_notes, 
                                a.callback_requested= b.callback_requested, 
                                a.acidRepsonse = b.acidRepsonse, 
                                a.formResponse = b.formResponse, 
                                a.getresponseResponse = b.getresponseResponse, 
                                a.vsoftResponse = b.vsoftResponse, 
                                a.respostingRule = b.respostingRule, 
                                a.formApiRuntime = b.formApiRuntime, 
                                a.formFullRuntime =b.formFullRuntime, 
                                a.formRulesRuntime= b.formRulesRuntime, 
                                a.crm =b.crm, 
                                a.crmPosted = b.crmPosted, 
                                a.lead_status= b.lead_status, 
                                a.dupetime = b.dupetime, 
                                a.payouttime = b.payouttime, 
                                a.phonechecktime= b.phonechecktime , 
                                a.predupetime= b.predupetime, 
                                a.prepayouttime= b.prepayouttime, 
                                a.resultcodetime = b.resultcodetime, 
                                a.tokentime = b.tokentime,
                                a.loopruntime= b.loopruntime, 
                                a.debt_types= b.debt_types, 
                                a.p_version = b.p_version, 
                                a.debt_hardships = b.debt_hardships, 
                                a.content_version= b.content_version, 
                                a.p_UID= b.p_UID, 
                                a.chat_hold = b.chat_hold, 
                                a.age = b.age, 
                                a.dncapifailure = b.dncapifailure, 
                                a.vs_id = b.vs_id, 
                                a.ac_phone_check  = b.ac_phone_check, 
                                a.acPass= b.acPass, 
                                a.tvsci = b.tvsci, 
                                a.user_agent = b.user_agent, 
                                a.eoresponse= b.eoresponse, 
                                a.blueshift= b.blueshift, 
                                a.eo_email_domain = b.eo_email_domain, 
                                a.eo_validation_status= b.eo_validation_status , 
                                a.phone_carrier= b.phone_carrier, 
                                a.phone_type = b.phone_type, 
                                a.tw_phone_carrier= b.tw_phone_carrier, 
                                a.tw_phone_type = b.tw_phone_type, 
                                a.fbclid = b.fbclid, 
                                a.tw_eror= b.tw_eror, 
                                a.convoso = b.convoso, 
                                a.ccxfer_results  = b.ccxfer_results, 
                                a.convsocheck= b.convsocheck, 
                                a.fbclid_response= b.fbclid_response,
                                a.vs_only = b.vs_only, 
                                a.llchecker = b.llchecker, 
                                a.prosper_signal = b.prosper_signal, 
                                a.sms = b.sms, 
                                a.last_updated = b.last_updated,
                                a.sent_to_signal = b.sent_to_signal , 
                                a.sent_to_signal_date = b.sent_to_signal_date,
                                a.sent_to_sms_camp = b.sent_to_sms_camp, 
                                a.sms_camp_response = b.sms_camp_response, 
                                a.trustformresponse = b.trustformresponse, 
                                a.trustformurl = b.trustformurl, 
                                a.sub10k = b.sub10k,
                                a.data_warehouse_insert_time = current_timestamp(2)
                        WHEN not matched THEN 
                        INSERT (
                                id,
                                dateACC , 
                                TimeACC , 
                                VanillaSoft_ID , 
                                VanillaSoft_Date , 
                                VanillaSoft_Time , 
                                VanisllaSoft_Results , 
                                EverFlow_Trans_Id , 
                                Offer_ID , 
                                Category , 
                                Channel , 
                                ad_Network , 
                                Aff_Id ,
                                Aff_Source, 
                                Sub_1, 
                                Sub_2 ,
                                Sub_3 ,
                                Sub_4 ,
                                Sub_5 ,
                                ip_address ,
                                First_Name ,
                                Last_Name , 
                                Email , 
                                Phone,
                                State ,
                                Zip ,
                                Klaviyo_ID ,
                                Debt_Amount ,
                                gclid ,
                                msclkid ,
                                Missed_Apts ,
                                chat_start ,
                                Quoted_date ,
                                Quoted_Time ,
                                bad_info ,
                                dnq ,
                                dnc ,
                                sold,
                                posted_to  ,
                                pushed_to ,
                                push_time ,
                                push_date,
                                tcpa_date ,
                                tcpa_screenshot ,
                                duplicate ,
                                payout ,
                                activecampaign_id,
                                ls_tracking,
                                vs_lead_status ,
                                tcpa_time ,
                                posted_to2 , 
                                website, 
                                op ,
                                result_code  ,
                                token ,
                                date_reactivated , 
                                chat_notes , 
                                original_lead_source , 
                                callback_notes , 
                                callback_requested , 
                                acidRepsonse , 
                                formResponse , 
                                getresponseResponse , 
                                vsoftResponse , 
                                respostingRule , 
                                formApiRuntime , 
                                formFullRuntime , 
                                formRulesRuntime , 
                                crm , 
                                crmPosted , 
                                lead_status , 
                                dupetime , 
                                payouttime , 
                                phonechecktime , 
                                predupetime , 
                                prepayouttime , 
                                resultcodetime , 
                                tokentime ,
                                loopruntime , 
                                debt_types , 
                                p_version , 
                                debt_hardships , 
                                content_version , 
                                p_UID , 
                                chat_hold , 
                                age , 
                                dncapifailure , 
                                vs_id , 
                                ac_phone_check , 
                                acPass , 
                                tvsci , 
                                user_agent , 
                                eoresponse , 
                                blueshift , 
                                eo_email_domain , 
                                eo_validation_status , 
                                phone_carrier , 
                                phone_type , 
                                tw_phone_carrier , 
                                tw_phone_type , 
                                fbclid , 
                                tw_eror , 
                                convoso , 
                                ccxfer_results , 
                                convsocheck , 
                                fbclid_response ,
                                vs_only , 
                                llchecker , 
                                prosper_signal , 
                                sms , 
                                last_updated,
                                sent_to_signal , 
                                sent_to_signal_date ,
                                sent_to_sms_camp , 
                                sms_camp_response , 
                                trustformresponse , 
                                trustformurl , 
                                sub10k,
                                data_warehouse_insert_time)
                          VALUES (
                                  b.id,
                                  b.dateACC , 
                                  b.TimeACC , 
                                  b.VanillaSoft_ID , 
                                  b.VanillaSoft_Date , 
                                  b.VanillaSoft_Time , 
                                  b.VanisllaSoft_Results , 
                                  b.EverFlow_Trans_Id , 
                                  b.Offer_ID , 
                                  b.Category , 
                                  b.Channel , 
                                  b.ad_Network , 
                                  b.Aff_Id ,
                                  b.Aff_Source ,
                                  b.Sub_1, 
                                  b.Sub_2 ,
                                  b.Sub_3 ,
                                  b.Sub_4 ,
                                  b.Sub_5 ,
                                  b.ip_address ,
                                  b.First_Name ,
                                  b.Last_Name  ,
                                  b.Email , 
                                  b.Phone,
                                  b.State ,
                                  b.Zip ,
                                  b.Klaviyo_ID ,
                                  b.Debt_Amount ,
                                  b.gclid ,
                                  b.msclkid ,
                                  b.Missed_Apts ,
                                  b.chat_start ,
                                  b.Quoted_date ,
                                  b.Quoted_Time ,
                                  b.bad_info ,
                                  b.dnq ,
                                  b.dnc ,
                                  b.sold,
                                  b.posted_to  ,
                                  b.pushed_to ,
                                  b.push_time ,
                                  b.push_date,
                                  b.tcpa_date ,
                                  b.tcpa_screenshot ,
                                  b.duplicate ,
                                  b.payout ,
                                  b.activecampaign_id,
                                  b.ls_tracking,
                                  b.vs_lead_status ,
                                  b.tcpa_time ,
                                  b.posted_to2 , 
                                  b.website ,
                                  b.op ,
                                  b.result_code  ,
                                  b.token ,
                                  b.date_reactivated , 
                                  b.chat_notes , 
                                  b.original_lead_source , 
                                  b.callback_notes , 
                                  b.callback_requested , 
                                  b.acidRepsonse , 
                                  b.formResponse , 
                                  b.getresponseResponse , 
                                  b.vsoftResponse , 
                                  b.respostingRule , 
                                  b.formApiRuntime , 
                                  b.formFullRuntime , 
                                  b.formRulesRuntime , 
                                  b.crm , 
                                  b.crmPosted , 
                                  b.lead_status , 
                                  b.dupetime , 
                                  b.payouttime , 
                                  b.phonechecktime , 
                                  b.predupetime , 
                                  b.prepayouttime , 
                                  b.resultcodetime , 
                                  b.tokentime ,
                                  b.loopruntime , 
                                  b.debt_types , 
                                  b.p_version , 
                                  b.debt_hardships , 
                                  b.content_version , 
                                  b.p_UID , 
                                  b.chat_hold , 
                                  b.age , 
                                  b.dncapifailure , 
                                  b.vs_id , 
                                  b.ac_phone_check , 
                                  b.acPass , 
                                  b.tvsci , 
                                  b.user_agent , 
                                  b.eoresponse , 
                                  b.blueshift , 
                                  b.eo_email_domain , 
                                  b.eo_validation_status , 
                                  b.phone_carrier , 
                                  b.phone_type , 
                                  b.tw_phone_carrier , 
                                  b.tw_phone_type , 
                                  b.fbclid , 
                                  b.tw_eror , 
                                  b.convoso , 
                                  b.ccxfer_results , 
                                  b.convsocheck , 
                                  b.fbclid_response ,
                                  b.vs_only , 
                                  b.llchecker , 
                                  b.prosper_signal , 
                                  b.sms , 
                                  b.last_updated,
                                  b.sent_to_signal , 
                                  b.sent_to_signal_date ,
                                b.sent_to_sms_camp , 
                                b.sms_camp_response , 
                                b.trustformresponse , 
                                b.trustformurl , 
                                b.sub10k,
                                current_timestamp(2))` 
         var merge_delta = snowflake.createStatement({sqlText: merge_statement});
         merge_delta.execute();
         
         
        // grab results 
        truncate_result = truncate_table.getNumRowsAffected();
        copy_result = copy_into.getNumRowsAffected();
        merge_delta_result = merge_delta.getNumRowsAffected();
        
        
        results.push([truncate_result,copy_result,merge_delta_result]);
        
        return results;
        
        
    $$